/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function ModelAvatar(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/avatar.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions);

    if (actions["GestureCheering"]) {
      actions["GestureCheering"].play();
    }
  }, [actions]);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[-1.75, -1.75, 0]}
      scale={0.8}
      rotation={[0, 250, 0]}
    >
      <group name="Scene">
        <group name="skeleton_#7">
          <group name="msm_glasses_3">
            <skinnedMesh
              name="msm_glasses_3_1"
              geometry={nodes.msm_glasses_3_1.geometry}
              material={materials.GlassRim_MTL}
              skeleton={nodes.msm_glasses_3_1.skeleton}
            />
            <skinnedMesh
              name="msm_glasses_3_2"
              geometry={nodes.msm_glasses_3_2.geometry}
              material={materials.Glass_MTL}
              skeleton={nodes.msm_glasses_3_2.skeleton}
            />
          </group>
          <group name="msm_hair_hat_C">
            <skinnedMesh
              name="msm_hair_hat_C_1"
              geometry={nodes.msm_hair_hat_C_1.geometry}
              material={materials.Jacket_MTL}
              skeleton={nodes.msm_hair_hat_C_1.skeleton}
            />
            <skinnedMesh
              name="msm_hair_hat_C_2"
              geometry={nodes.msm_hair_hat_C_2.geometry}
              material={materials.Collar_MTL}
              skeleton={nodes.msm_hair_hat_C_2.skeleton}
            />
            <skinnedMesh
              name="msm_hair_hat_C_3"
              geometry={nodes.msm_hair_hat_C_3.geometry}
              material={materials.Hair_MTL}
              skeleton={nodes.msm_hair_hat_C_3.skeleton}
            />
          </group>
          <skinnedMesh
            name="msm_head_main"
            geometry={nodes.msm_head_main.geometry}
            material={materials.Skin_MTL}
            skeleton={nodes.msm_head_main.skeleton}
          />
          <group name="msm_pants_No3">
            <skinnedMesh
              name="msm_pants_No3_1"
              geometry={nodes.msm_pants_No3_1.geometry}
              material={materials.Pants_MTL}
              skeleton={nodes.msm_pants_No3_1.skeleton}
            />
            <skinnedMesh
              name="msm_pants_No3_2"
              geometry={nodes.msm_pants_No3_2.geometry}
              material={materials.Jeans_Pockets_MTL}
              skeleton={nodes.msm_pants_No3_2.skeleton}
            />
            <skinnedMesh
              name="msm_pants_No3_3"
              geometry={nodes.msm_pants_No3_3.geometry}
              material={materials.Socks_MTL}
              skeleton={nodes.msm_pants_No3_3.skeleton}
            />
          </group>
          <skinnedMesh
            name="msm_shoes_No16"
            geometry={nodes.msm_shoes_No16.geometry}
            material={materials.Shoes_MTL}
            skeleton={nodes.msm_shoes_No16.skeleton}
          />
          <group name="msm_top_No31">
            <skinnedMesh
              name="msm_top_No31_1"
              geometry={nodes.msm_top_No31_1.geometry}
              material={materials.Skin_MTL}
              skeleton={nodes.msm_top_No31_1.skeleton}
            />
            <skinnedMesh
              name="msm_top_No31_2"
              geometry={nodes.msm_top_No31_2.geometry}
              material={materials.Sweater_MTL}
              skeleton={nodes.msm_top_No31_2.skeleton}
            />
            <skinnedMesh
              name="msm_top_No31_3"
              geometry={nodes.msm_top_No31_3.geometry}
              material={materials.Shirt_MTL}
              skeleton={nodes.msm_top_No31_3.skeleton}
            />
            <skinnedMesh
              name="msm_top_No31_4"
              geometry={nodes.msm_top_No31_4.geometry}
              material={materials.Jacket_MTL}
              skeleton={nodes.msm_top_No31_4.skeleton}
            />
            <skinnedMesh
              name="msm_top_No31_5"
              geometry={nodes.msm_top_No31_5.geometry}
              material={materials.Collar_MTL}
              skeleton={nodes.msm_top_No31_5.skeleton}
            />
          </group>
          <primitive object={nodes.Root} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/avatar.glb");
