/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Bee.glb --transform 
Files: Bee.glb [20.18MB] > D:\WEB BASE\NEXT\hi-aziz\public\Bee-transformed.glb [1.89MB] (91%)
*/

"use client";

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function ModelBee(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/Bee-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  console.log(materials, "AKSIIII");

  useEffect(() => {
    actions["_bee_hover"]?.play();
  }, [actions]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.05}
      position={[0, -0.4, 0]}
    >
      <group rotation={[-Math.PI / 0.1, 155, 0]}>
        <group name="skeletal1" scale={0.01}>
          <primitive object={nodes.root_jnt2} />
        </group>
        <skinnedMesh
          name="1645859359680_0"
          geometry={nodes["1645859359680_0"].geometry}
          material={materials.mtl_bee41}
          skeleton={nodes["1645859359680_0"].skeleton}
          scale={0.01}
          // rotation={[0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Bee-transformed.glb");
