/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Digital screen official (https://sketchfab.com/ck212575)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-environments-01-7c222acff4ec452c8cc45be764650112
Title: low poly environments 01
*/

"use client";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function RoomModel(props) {
  const { nodes, materials } = useGLTF("/room.glb");
  return (
    <group {...props} dispose={null} position={[10, -2, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.Material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/room.glb");
