/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\room01.glb --transform 
Files: .\public\room01.glb [4.98MB] > C:\PORTFILIO\hi-aziz\room01-transformed.glb [157.02KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room01-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.daun.geometry} material={materials.PaletteMaterial001} position={[2.298, 0.736, -0.602]} rotation={[Math.PI / 2, 0, 0]} scale={0.394} />
      <mesh geometry={nodes.batu.geometry} material={materials.PaletteMaterial001} position={[2.298, 0.736, -0.602]} rotation={[Math.PI / 2, 0, 0]} scale={0.394} />
      <mesh geometry={nodes.blinn1.geometry} material={materials.PaletteMaterial002} position={[2.298, 0.736, -0.602]} rotation={[Math.PI / 2, 0, 0]} scale={0.394} />
    </group>
  )
}

useGLTF.preload('/room01-transformed.glb')
